/**
 * Syntropy Health tool definitions for the OpenClaw agent.
 *
 * Each tool wraps a Syntropy MCP tool, calling it via HTTP with the
 * user's stored API token (standard Bearer auth).
 *
 * ──────────────────────────────────────────────────────────────────────────
 * Schema source of truth (#200)
 * ──────────────────────────────────────────────────────────────────────────
 * The architecture of record is F.1 = (c) Layered
 * (docs/superpowers/plans/2026-05-11-sj-mcp-center-layered.md): ONE schema
 * source of truth, every surface regenerated from it. For this file that
 * source is the SJ tool manifests, reaching here as the GENERATED roster
 * (`./generated/tool-roster.generated.ts`, regenerated by
 * `npm run codegen:openclaw-tool-roster` in the monorepo's `shared/schemas/`
 * from the PINNED Syntropy-Journals submodule commit).
 *
 * What is roster-derived vs local:
 *
 *   ROSTER-DERIVED (generated, verbatim from the manifest):
 *     - membership (which tools exist)
 *     - `mcpToolName` (the SJ-side wire name to call)
 *     - `description` (what the agent reads to pick a tool)
 *
 *   LOCAL (this file, because the manifest does not carry them yet):
 *     - `label` (a UI string that exists nowhere upstream)
 *     - `parameters` (TypeBox schemas; the manifest names an
 *       `input_model_class` but those Pydantic input models are not exported
 *       into `shared/schemas/syntropy.schema.json` — zero `*Input` defs).
 *       Exporting them upstream is the follow-up that completes F.1 here.
 *
 *   UPSTREAM BUT NOT PROPAGATED (known gap, tracked in the roster-derivation
 *   follow-up issue): the manifests also carry `prompt_hints.when_to_call` /
 *   `do_not_call` (negative routing guidance) and `available_channels` (SJ's
 *   channel-reachability control). Neither reaches the roster yet, so the
 *   derivation below is complete over the roster's fields — not over
 *   everything the manifest knows.
 *
 * THE GATE IS THE TYPE. `TOOL_LOCALS` is a `Record<ImplementedName,
 * ToolLocal>` where `ImplementedName` = every rostered name not explicitly
 * deferred in `NOT_YET_IMPLEMENTED`:
 *   - a rostered tool with no local entry   → TS2739 (missing property)
 *   - a local entry that is not rostered    → excess-property compile error
 * Either direction fails `tsgo`. This is what killed the historical drift:
 * this file used to hand-maintain the whole list and shipped deprecated
 * `syntropy_chat` while omitting live `syntropy_my_protocols`. It also means
 * a hand-typo in `mcpToolName`/`description` is impossible — those fields no
 * longer exist in this file to typo.
 *
 * Enum schemas (`MealTypeSchema`, etc.) are imported from `./generated/` —
 * auto-generated from `shared/schemas/enums.json`. The SJ MCP server
 * validates payloads server-side; parameter mismatches manifest as
 * user-visible 4xx responses, so keep enums as TypeBox literal unions.
 */

import type { AgentToolResult } from "@mariozechner/pi-agent-core";
import { Type, type TObject } from "@sinclair/typebox";
import { callSyntropyTool, type SyntropyToolResult } from "./client.js";
import { MealTypeSchema } from "./generated/enums.generated.js";
import { TOOL_ROSTER, type RosterToolName } from "./generated/tool-roster.generated.js";
import type { Tracer } from "./tracer.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toAgentResult(res: SyntropyToolResult): AgentToolResult<unknown> {
  if (!res.ok) {
    return {
      content: [{ type: "text", text: `Error: ${res.error ?? "Unknown error"}` }],
      details: { error: res.error },
    };
  }
  const text = typeof res.data === "string" ? res.data : JSON.stringify(res.data, null, 2);
  return { content: [{ type: "text", text }], details: res.data };
}

// ---------------------------------------------------------------------------
// #200 — membership contract
// ---------------------------------------------------------------------------

/** A fully assembled tool definition: roster fields + local fields. */
interface ToolDef {
  readonly name: string;
  readonly label: string;
  readonly description: string;
  readonly parameters: TObject;
  readonly mcpToolName: string;
}

/**
 * Rostered tools this file deliberately does NOT implement yet.
 *
 * #200 fixes the CONTRACT MECHANISM; it does not expand the agent's tool
 * surface (CTO ruling: no new tool rides this ticket). `syntropy_my_protocols`
 * is live and non-deprecated upstream but has never been exposed here, and
 * wiring it needs `parameters` authored against its input contract — real
 * work with a user-visible 4xx failure mode if guessed.
 *
 * Listing a name here is load-bearing, and DEFERRING IS NOT FREE: moving a
 * tool from implemented to deferred requires (1) deleting its `TOOL_LOCALS`
 * entry (the Record type forces it) and (2) editing the pinned expectation in
 * `tools.test.ts` (which asserts this list's exact contents). Shrinking the
 * agent surface is a two-file conscious act, never a silent side effect.
 *
 * When the SJ submodule pin advances and brings a NEW manifest tool, the
 * Record below breaks the build (TS2739) until the tool is implemented or
 * consciously added here. Silence is not an option in either direction.
 */
export const NOT_YET_IMPLEMENTED = [
  "syntropy_my_protocols",
] as const satisfies readonly RosterToolName[];

type PendingName = (typeof NOT_YET_IMPLEMENTED)[number];

/** Every rostered tool this file must supply locals for. */
type ImplementedName = Exclude<RosterToolName, PendingName>;

/** What the manifest does NOT carry (yet) — supplied locally per tool. */
interface ToolLocal {
  readonly label: string;
  readonly parameters: TObject;
}

// ---------------------------------------------------------------------------
// Local fields — label + TypeBox parameters for every implemented tool.
// Membership, mcpToolName, and description come from the generated roster;
// they are deliberately NOT repeated here (nothing hand-kept can drift).
// ---------------------------------------------------------------------------

/**
 * P3-A4: the DECLARED type of TOOL_LOCALS, exported type-only so the
 * compile-gate probe (tools.gate-probe.ts) can assert the gate is still
 * ARMED. If this Record is ever widened (e.g. to Record<string, ToolLocal>),
 * the probe's @ts-expect-error directives become unused and tsgo fails —
 * converting the gate's in-session mutation proofs into a standing CI fact.
 */
export type ToolLocalsShape = Record<ImplementedName, ToolLocal>;

const TOOL_LOCALS: ToolLocalsShape = {
  syntropy_log_food: {
    label: "Log Food",
    parameters: Type.Object({
      food_name: Type.String({ description: "Food item name or description" }),
      meal_type: Type.Optional(MealTypeSchema),
      calories: Type.Optional(Type.Number({ description: "Calories" })),
      protein: Type.Optional(Type.Number({ description: "Protein in grams" })),
      carbs: Type.Optional(Type.Number({ description: "Carbs in grams" })),
      fat: Type.Optional(Type.Number({ description: "Fat in grams" })),
      notes: Type.Optional(Type.String({ description: "Additional notes" })),
    }),
  },
  syntropy_log_checkin: {
    label: "Health Check-in",
    parameters: Type.Object({
      content: Type.String({ description: "Free-text health check-in" }),
    }),
  },
  syntropy_diet_score: {
    label: "Diet Score",
    parameters: Type.Object({
      days: Type.Optional(Type.Number({ description: "Days to score (default: 30, max: 365)" })),
    }),
  },
  syntropy_diet_gap: {
    label: "Diet Gap Analysis",
    parameters: Type.Object({
      days: Type.Optional(Type.Number({ description: "Days to analyze (default: 7, max: 365)" })),
    }),
  },
  syntropy_health_snapshot: {
    label: "Health Snapshot",
    parameters: Type.Object({
      days: Type.Optional(Type.Number({ description: "Days (default: 30, max: 365)" })),
    }),
  },
  syntropy_analyze_food: {
    label: "Analyze Food",
    parameters: Type.Object({
      food_text: Type.String({ description: "Natural language food description" }),
      meal_type: Type.Optional(MealTypeSchema),
    }),
  },
  syntropy_health_profile: {
    label: "Health Profile",
    parameters: Type.Object({}),
  },
  syntropy_my_checkins: {
    label: "Recent Check-ins",
    parameters: Type.Object({
      limit: Type.Optional(Type.Number({ description: "Count (default: 10, max: 50)" })),
    }),
  },
};

// ---------------------------------------------------------------------------
// Assembly — TOOL_DEFS is DERIVED, not declared.
//
// No runtime empty-roster guard, deliberately (QG2-14): an empty roster makes
// `RosterToolName = never`, which fails the `NOT_YET_IMPLEMENTED` satisfies
// clause and every `TOOL_LOCALS` key at COMPILE time — a runtime throw here
// is unreachable in any typechecked build, and at module top level it would
// crash extension load rather than degrade. The generator additionally
// refuses to emit an empty roster.
// ---------------------------------------------------------------------------

/** Roster entries whose names are implemented (i.e. not deferred). */
type ImplementedEntry = Extract<(typeof TOOL_ROSTER)[number], { name: ImplementedName }>;

const PENDING = new Set<string>(NOT_YET_IMPLEMENTED);

/**
 * The assembled tool surface: roster (name, mcpToolName, description) joined
 * with locals (label, parameters). Exported so tests can pin the derivation.
 */
export const TOOL_DEFS: readonly ToolDef[] = TOOL_ROSTER.filter(
  (t): t is ImplementedEntry => !PENDING.has(t.name),
).map((t) => ({
  name: t.name,
  label: TOOL_LOCALS[t.name].label,
  description: t.description,
  parameters: TOOL_LOCALS[t.name].parameters,
  mcpToolName: t.mcpToolName,
}));

// ---------------------------------------------------------------------------
// Factory — creates tools bound to a specific user's auth token
// ---------------------------------------------------------------------------

export function createAllTools(
  baseUrl: string,
  authToken: string,
  // Optional Braintrust tracer (PHI-safe). When omitted (the default-OFF
  // path), tool execution calls the MCP transport directly — byte-identical
  // behavior, no braintrust code loaded.
  tracer?: Tracer,
): Array<{
  name: string;
  label: string;
  description: string;
  parameters: TObject;
  execute: (toolCallId: string, args: unknown) => Promise<AgentToolResult<unknown>>;
}> {
  return TOOL_DEFS.map((def) => ({
    name: def.name,
    label: def.label,
    description: def.description,
    parameters: def.parameters,
    async execute(_toolCallId: string, args: unknown): Promise<AgentToolResult<unknown>> {
      const params = (args ?? {}) as Record<string, unknown>;
      const call = () => callSyntropyTool(baseUrl, authToken, def.mcpToolName, params);
      const result = tracer
        ? await tracer.traceMcp("Syntropy", def.mcpToolName, params, call)
        : await call();
      return toAgentResult(result);
    },
  }));
}
